### ISSUE TITLE
Question to assumption in code:

### ISSUE THREAD

**Issue by florianjehn** [allfed/animal-feed-model#5]
- Why "dairy_beef_mother_ratio = dairy_cows / beef_cows"? Are all beef cows male?

**Comment by k-r-a-s-s** [comment]
No, not all beef cows are male.

yeah there is a bit going on here to simplify the [stats: ](https://downloads.usda.library.cornell.edu/usda-esmis/files/h702q636h/tq57pz24k/cz30r103f/catl0722.pdf), with some elaboration [here: ](https://www.nass.usda.gov/Newsroom/2022/01-31-2022.php)

The source data just lists: calves, heifers, steers etc. It doesn't list whether they are destined for beef or dairy production. I've used the ratio of beef to dairy mothers to estimate which will be in each track. 

Dairy breed cows which are male will end up in the beef track, hence: 
    cattle_in_beef_track = (
        dairy_calf_boys + beef_calves + beef_steers + beef_cows + beef_heifers
    )
    cattle_in_dairy_track = dairy_calf_girls + dairy_cows + dairy_heifers
    
Note: steers = castrated male, and dairy_steers doesn't exist as male cows can't make milk


All this said, I think you have highlighted an error! I think it should be a percentage not a ratio
dairy_mother_percent = dairy_cows / (beef_cows+dairy_cows)
