### ISSUE TITLE
Unused variables

### ISSUE THREAD

**Issue by florianjehn** [allfed/animal-feed-model#6]
bulls = df.loc["Bulls 500 pounds and over", "Qty"]
cattle_on_feed = df.loc["Cattle on feed", "Qty"]

Are defined, but never used. Not sure what the second is, but is it intentional that you don't account for bulls?

**Comment by k-r-a-s-s** [comment]
Intentially ignored bulls due to their low numbers (1.5% of slaughter). We can include them if useful. 
Those values are artifacts of the 'big import' I did at the start of all the NASS/USDA data. I will remove them now.
